/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 122
 * 
 * @export
 * @interface CacheUser
 */
export interface CacheUser {
    /**
     * 
     * @type {string}
     * @memberof CacheUser
     */
    'account'?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof CacheUser
     */
    'appPerms'?: Set<string>;
    /**
     * 
     * @type {string}
     * @memberof CacheUser
     */
    'id'?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof CacheUser
     */
    'pcPerms'?: Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof CacheUser
     */
    'perms'?: Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof CacheUser
     */
    'roles'?: Set<string>;
    /**
     * 
     * @type {string}
     * @memberof CacheUser
     */
    'token'?: string;
    /**
     * 
     * @type {string}
     * @memberof CacheUser
     */
    'userName'?: string;
}

