/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 122
 * 
 * @export
 * @interface ChangePasswordVo
 */
export interface ChangePasswordVo {
    /**
     * 新密码
     * @type {string}
     * @memberof ChangePasswordVo
     */
    'newPassword': string;
    /**
     * 原密码
     * @type {string}
     * @memberof ChangePasswordVo
     */
    'oldPassword': string;
    /**
     * 用户id
     * @type {string}
     * @memberof ChangePasswordVo
     */
    'userId': string;
}

