/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// 789
// @ts-ignore
import type { CheckSetFlowUserRelateDto } from './check-set-flow-user-relate-dto';

/**
 * 122
 * 
 * @export
 * @interface CheckSetFlowDto
 */
export interface CheckSetFlowDto {
    /**
     * 审核流关联信息列表
     * @type {Array<CheckSetFlowUserRelateDto>}
     * @memberof CheckSetFlowDto
     */
    'checkSetFlowUserRelateDtos'?: Array<CheckSetFlowUserRelateDto>;
    /**
     * 审核设置id
     * @type {string}
     * @memberof CheckSetFlowDto
     */
    'checkSetId'?: string;
    /**
     * 主键采用uuid
     * @type {string}
     * @memberof CheckSetFlowDto
     */
    'id'?: string;
    /**
     * 备注
     * @type {string}
     * @memberof CheckSetFlowDto
     */
    'remark'?: string;
    /**
     * 排序
     * @type {number}
     * @memberof CheckSetFlowDto
     */
    'sort'?: number;
    /**
     * 审核流类型_1：单人，2：多人
     * @type {number}
     * @memberof CheckSetFlowDto
     */
    'type'?: number;
    /**
     * 乐观锁
     * @type {number}
     * @memberof CheckSetFlowDto
     */
    'version'?: number;
}

