/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 122
 * 
 * @export
 * @interface CheckDto
 */
export interface CheckDto {
    /**
     * 主键采用uuid
     * @type {string}
     * @memberof CheckDto
     */
    'id'?: string;
    /**
     * 操作人id
     * @type {string}
     * @memberof CheckDto
     */
    'operatorId'?: string;
    /**
     * 操作人名称
     * @type {string}
     * @memberof CheckDto
     */
    'operatorName'?: string;
    /**
     * 备注
     * @type {string}
     * @memberof CheckDto
     */
    'remark'?: string;
    /**
     * 状态_1：待审核_2：审核通过，3：审核驳回
     * @type {number}
     * @memberof CheckDto
     */
    'status'?: number;
}

