/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 122
 * 
 * @export
 * @interface CheckNotAuditNumVo
 */
export interface CheckNotAuditNumVo {
    /**
     * 订单价格未审核数量
     * @type {number}
     * @memberof CheckNotAuditNumVo
     */
    'orderPriceNoAuditCount'?: number;
    /**
     * 产品价格未审核数量
     * @type {number}
     * @memberof CheckNotAuditNumVo
     */
    'productPriceNoAuditCount'?: number;
    /**
     * 产品库存未审核数量
     * @type {number}
     * @memberof CheckNotAuditNumVo
     */
    'productStockNoAuditCount'?: number;
    /**
     * 调度单单价未审核数量
     * @type {number}
     * @memberof CheckNotAuditNumVo
     */
    'schedulingPriceNoAuditCount'?: number;
}

