/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 122
 * 
 * @export
 * @interface CheckFlowUserRelateVo
 */
export interface CheckFlowUserRelateVo {
    /**
     * 添加时间
     * @type {string}
     * @memberof CheckFlowUserRelateVo
     */
    'addTime'?: string;
    /**
     * 信息审核流id
     * @type {string}
     * @memberof CheckFlowUserRelateVo
     */
    'checkFlowId'?: string;
    /**
     * 逻辑删除_0_未删除_1_已删除
     * @type {number}
     * @memberof CheckFlowUserRelateVo
     */
    'deleted'?: number;
    /**
     * 编辑时间
     * @type {string}
     * @memberof CheckFlowUserRelateVo
     */
    'editTime'?: string;
    /**
     * 主键采用uuid
     * @type {string}
     * @memberof CheckFlowUserRelateVo
     */
    'id'?: string;
    /**
     * 备注
     * @type {string}
     * @memberof CheckFlowUserRelateVo
     */
    'remark'?: string;
    /**
     * 审核流类型状态_1：待审核，2：通过，3：驳回
     * @type {number}
     * @memberof CheckFlowUserRelateVo
     */
    'status'?: number;
    /**
     * 审核流类型状态_1：待审核，2：通过，3：驳回
     * @type {string}
     * @memberof CheckFlowUserRelateVo
     */
    'statusName'?: string;
    /**
     * 用户id
     * @type {string}
     * @memberof CheckFlowUserRelateVo
     */
    'userId'?: string;
    /**
     * 用户名称
     * @type {string}
     * @memberof CheckFlowUserRelateVo
     */
    'userName'?: string;
    /**
     * 乐观锁
     * @type {number}
     * @memberof CheckFlowUserRelateVo
     */
    'version'?: number;
}

