/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 122
 * 
 * @export
 * @interface CheckVo
 */
export interface CheckVo {
    /**
     * 添加时间
     * @type {string}
     * @memberof CheckVo
     */
    'addTime'?: string;
    /**
     * 客户卸货点名称
     * @type {string}
     * @memberof CheckVo
     */
    'addressName'?: string;
    /**
     * 审核价
     * @type {string}
     * @memberof CheckVo
     */
    'checkUnitPrice'?: string;
    /**
     * 当前基准价
     * @type {string}
     * @memberof CheckVo
     */
    'currProductPrice'?: string;
    /**
     * 客户名称
     * @type {string}
     * @memberof CheckVo
     */
    'customerName'?: string;
    /**
     * 逻辑删除_0_未删除_1_已删除
     * @type {number}
     * @memberof CheckVo
     */
    'deleted'?: number;
    /**
     * 计划配送日期
     * @type {string}
     * @memberof CheckVo
     */
    'deliveryDate'?: string;
    /**
     * 编辑时间
     * @type {string}
     * @memberof CheckVo
     */
    'editTime'?: string;
    /**
     * 主键采用uuid
     * @type {string}
     * @memberof CheckVo
     */
    'id'?: string;
    /**
     * 操作人id
     * @type {string}
     * @memberof CheckVo
     */
    'operatorId'?: string;
    /**
     * 操作人名称
     * @type {string}
     * @memberof CheckVo
     */
    'operatorName'?: string;
    /**
     * 订单日期
     * @type {string}
     * @memberof CheckVo
     */
    'orderDate'?: string;
    /**
     * 订单号
     * @type {string}
     * @memberof CheckVo
     */
    'orderNumber'?: string;
    /**
     * 订单量t
     * @type {number}
     * @memberof CheckVo
     */
    'orderWeight'?: number;
    /**
     * 审核时基准价
     * @type {string}
     * @memberof CheckVo
     */
    'oriProductPrice'?: string;
    /**
     * 产品名称
     * @type {string}
     * @memberof CheckVo
     */
    'productName'?: string;
    /**
     * 申请原因
     * @type {string}
     * @memberof CheckVo
     */
    'reason'?: string;
    /**
     * 备注
     * @type {string}
     * @memberof CheckVo
     */
    'remark'?: string;
    /**
     * 业务员名称
     * @type {string}
     * @memberof CheckVo
     */
    'salesmanName'?: string;
    /**
     * 状态_1：待审核_2：审核通过，3：审核驳回
     * @type {number}
     * @memberof CheckVo
     */
    'status'?: number;
    /**
     * 单价元(t)
     * @type {number}
     * @memberof CheckVo
     */
    'unitPrice'?: number;
    /**
     * 乐观锁
     * @type {number}
     * @memberof CheckVo
     */
    'version'?: number;
}

