/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 122
 * 
 * @export
 * @interface CheckSetFlowUserRelateDto
 */
export interface CheckSetFlowUserRelateDto {
    /**
     * 审核流设置id
     * @type {string}
     * @memberof CheckSetFlowUserRelateDto
     */
    'checkSetFlowId'?: string;
    /**
     * 主键采用uuid
     * @type {string}
     * @memberof CheckSetFlowUserRelateDto
     */
    'id'?: string;
    /**
     * 备注
     * @type {string}
     * @memberof CheckSetFlowUserRelateDto
     */
    'remark'?: string;
    /**
     * 用户id
     * @type {string}
     * @memberof CheckSetFlowUserRelateDto
     */
    'userId'?: string;
    /**
     * 用户名称
     * @type {string}
     * @memberof CheckSetFlowUserRelateDto
     */
    'userName'?: string;
    /**
     * 乐观锁
     * @type {number}
     * @memberof CheckSetFlowUserRelateDto
     */
    'version'?: number;
}

