/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// 789
// @ts-ignore
import type { CheckSetFlowDto } from './check-set-flow-dto';

/**
 * 122
 * 
 * @export
 * @interface CheckSetDto
 */
export interface CheckSetDto {
    /**
     * 审核流列表
     * @type {Array<CheckSetFlowDto>}
     * @memberof CheckSetDto
     */
    'checkSetFlowDtos'?: Array<CheckSetFlowDto>;
    /**
     * 主键采用uuid
     * @type {string}
     * @memberof CheckSetDto
     */
    'id'?: string;
    /**
     * 审核名称
     * @type {string}
     * @memberof CheckSetDto
     */
    'name'?: string;
    /**
     * 备注
     * @type {string}
     * @memberof CheckSetDto
     */
    'remark'?: string;
    /**
     * 审核类型_1：储槽业务更改，2：基准价格审核，3：订单低于基准价格，4：调度提货点单价
     * @type {number}
     * @memberof CheckSetDto
     */
    'type'?: number;
    /**
     * 乐观锁
     * @type {number}
     * @memberof CheckSetDto
     */
    'version'?: number;
}

