/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// 789
// @ts-ignore
import type { CheckFlowUserRelateVo } from './check-flow-user-relate-vo';

/**
 * 122
 * 
 * @export
 * @interface CheckFlowVo
 */
export interface CheckFlowVo {
    /**
     * 添加时间
     * @type {string}
     * @memberof CheckFlowVo
     */
    'addTime'?: string;
    /**
     * 关联信息列表
     * @type {Array<CheckFlowUserRelateVo>}
     * @memberof CheckFlowVo
     */
    'checkFlowUserRelateVos'?: Array<CheckFlowUserRelateVo>;
    /**
     * 信息审核id
     * @type {string}
     * @memberof CheckFlowVo
     */
    'checkId'?: string;
    /**
     * 审核设置id
     * @type {string}
     * @memberof CheckFlowVo
     */
    'checkSetId'?: string;
    /**
     * 逻辑删除_0_未删除_1_已删除
     * @type {number}
     * @memberof CheckFlowVo
     */
    'deleted'?: number;
    /**
     * 编辑时间
     * @type {string}
     * @memberof CheckFlowVo
     */
    'editTime'?: string;
    /**
     * 首次生成_1：是，2：否
     * @type {number}
     * @memberof CheckFlowVo
     */
    'firstEdit'?: number;
    /**
     * 主键采用uuid
     * @type {string}
     * @memberof CheckFlowVo
     */
    'id'?: string;
    /**
     * 备注
     * @type {string}
     * @memberof CheckFlowVo
     */
    'remark'?: string;
    /**
     * 排序
     * @type {number}
     * @memberof CheckFlowVo
     */
    'sort'?: number;
    /**
     * 审核流类型状态_1：待审核，2：通过，3：驳回
     * @type {number}
     * @memberof CheckFlowVo
     */
    'status'?: number;
    /**
     * 审核流类型状态_1：待审核，2：通过，3：驳回
     * @type {string}
     * @memberof CheckFlowVo
     */
    'statusName'?: string;
    /**
     * 审核流类型_1：单人，2：多人
     * @type {number}
     * @memberof CheckFlowVo
     */
    'type'?: number;
    /**
     * 乐观锁
     * @type {number}
     * @memberof CheckFlowVo
     */
    'version'?: number;
}

