/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 122
 * 
 * @export
 * @interface CheckSetVo
 */
export interface CheckSetVo {
    /**
     * 添加时间
     * @type {string}
     * @memberof CheckSetVo
     */
    'addTime'?: string;
    /**
     * 逻辑删除_0_未删除_1_已删除
     * @type {number}
     * @memberof CheckSetVo
     */
    'deleted'?: number;
    /**
     * 编辑时间
     * @type {string}
     * @memberof CheckSetVo
     */
    'editTime'?: string;
    /**
     * 主键采用uuid
     * @type {string}
     * @memberof CheckSetVo
     */
    'id'?: string;
    /**
     * 审核名称
     * @type {string}
     * @memberof CheckSetVo
     */
    'name'?: string;
    /**
     * 备注
     * @type {string}
     * @memberof CheckSetVo
     */
    'remark'?: string;
    /**
     * 审核类型_1：储槽业务更改，2：基准价格审核，3：订单低于基准价格，4：调度提货点单价
     * @type {number}
     * @memberof CheckSetVo
     */
    'type'?: number;
    /**
     * 乐观锁
     * @type {number}
     * @memberof CheckSetVo
     */
    'version'?: number;
}

