/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 122
 * 
 * @export
 * @interface DictItemValueDetail
 */
export interface DictItemValueDetail {
    /**
     * 字典表项数据——title
     * @type {string}
     * @memberof DictItemValueDetail
     */
    'title'?: string;
    /**
     * 字典表项数据——value
     * @type {string}
     * @memberof DictItemValueDetail
     */
    'value'?: string;
}

