/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 122
 * 
 * @export
 * @interface DictItemVo
 */
export interface DictItemVo {
    /**
     * 字典表id
     * @type {string}
     * @memberof DictItemVo
     */
    'dictId': string;
    /**
     * 是否固定_0否_1是
     * @type {boolean}
     * @memberof DictItemVo
     */
    'fixed'?: boolean;
    /**
     * 字典项表Id
     * @type {string}
     * @memberof DictItemVo
     */
    'id'?: string;
    /**
     * 名称
     * @type {string}
     * @memberof DictItemVo
     */
    'name': string;
    /**
     * 用于记录操作日志的字段,删除则传被删除对象的名称,新增则传新增的名称,编辑则传原字段值+新字段值_编辑删除是必传
     * @type {string}
     * @memberof DictItemVo
     */
    'param'?: string;
    /**
     * 备注
     * @type {string}
     * @memberof DictItemVo
     */
    'remark'?: string;
    /**
     * 编码
     * @type {string}
     * @memberof DictItemVo
     */
    'value': string;
    /**
     * 乐观锁,编辑必传
     * @type {number}
     * @memberof DictItemVo
     */
    'version'?: number;
}

