/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 122
 * 
 * @export
 * @interface DictVo
 */
export interface DictVo {
    /**
     * 字典key
     * @type {string}
     * @memberof DictVo
     */
    'dictKey': string;
    /**
     * 字典名称
     * @type {string}
     * @memberof DictVo
     */
    'dictName': string;
    /**
     * 是否固定_0否_1是
     * @type {boolean}
     * @memberof DictVo
     */
    'fixed'?: boolean;
    /**
     * 字典表Id
     * @type {string}
     * @memberof DictVo
     */
    'id'?: string;
    /**
     * 用于记录操作日志的字段,删除则传被删除对象的名称,新增则传新增的名称,编辑则传原字段值+新字段值_编辑删除是必传
     * @type {string}
     * @memberof DictVo
     */
    'param'?: string;
    /**
     * 备注
     * @type {string}
     * @memberof DictVo
     */
    'remark'?: string;
    /**
     * 
     * @type {string}
     * @memberof DictVo
     */
    'titleJson'?: string;
    /**
     * 字典列名称json字符串
     * @type {Array<string>}
     * @memberof DictVo
     */
    'titles'?: Array<string>;
    /**
     * 乐观锁,编辑必传
     * @type {number}
     * @memberof DictVo
     */
    'version'?: number;
}

