/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// 789
// @ts-ignore
import type { DictItemValueDetail } from './dict-item-value-detail';

/**
 * 122
 * 
 * @export
 * @interface DictItemDto
 */
export interface DictItemDto {
    /**
     * 添加时间
     * @type {string}
     * @memberof DictItemDto
     */
    'addTime'?: string;
    /**
     * 字典id
     * @type {string}
     * @memberof DictItemDto
     */
    'dictId': string;
    /**
     * 修改时间
     * @type {string}
     * @memberof DictItemDto
     */
    'editTime'?: string;
    /**
     * 是否固定_0否_1是
     * @type {boolean}
     * @memberof DictItemDto
     */
    'fixed'?: boolean;
    /**
     * 字典项表Id
     * @type {string}
     * @memberof DictItemDto
     */
    'id'?: string;
    /**
     * 字典列数据
     * @type {Array<DictItemValueDetail>}
     * @memberof DictItemDto
     */
    'items'?: Array<DictItemValueDetail>;
    /**
     * 名称
     * @type {string}
     * @memberof DictItemDto
     */
    'name': string;
    /**
     * 备注
     * @type {string}
     * @memberof DictItemDto
     */
    'remark'?: string;
    /**
     * 值
     * @type {string}
     * @memberof DictItemDto
     */
    'value': string;
}

