/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 122
 * 
 * @export
 * @interface DictDto
 */
export interface DictDto {
    /**
     * 添加时间
     * @type {string}
     * @memberof DictDto
     */
    'addTime'?: string;
    /**
     * 字典key
     * @type {string}
     * @memberof DictDto
     */
    'dictKey': string;
    /**
     * 字典名称
     * @type {string}
     * @memberof DictDto
     */
    'dictName': string;
    /**
     * 修改时间
     * @type {string}
     * @memberof DictDto
     */
    'editTime'?: string;
    /**
     * 是否固定_0否_1是
     * @type {boolean}
     * @memberof DictDto
     */
    'fixed'?: boolean;
    /**
     * 字典表Id
     * @type {string}
     * @memberof DictDto
     */
    'id'?: string;
    /**
     * 是否独立展示_0否_1是_（即单独小页面展示）
     * @type {boolean}
     * @memberof DictDto
     */
    'isIndependent'?: boolean;
    /**
     * 备注
     * @type {string}
     * @memberof DictDto
     */
    'remark'?: string;
    /**
     * 字典列名称
     * @type {Array<string>}
     * @memberof DictDto
     */
    'titles'?: Array<string>;
}

