/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 122
 * 
 * @export
 * @interface FileUploadBase64Request
 */
export interface FileUploadBase64Request {
    /**
     * 文件流
     * @type {string}
     * @memberof FileUploadBase64Request
     */
    'base64': string;
    /**
     * 文件名称
     * @type {string}
     * @memberof FileUploadBase64Request
     */
    'fileName'?: string;
}

