/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 122
 * 
 * @export
 * @interface IdsDto
 */
export interface IdsDto {
    /**
     * 要删除的id
     * @type {Array<string>}
     * @memberof IdsDto
     */
    'ids'?: Array<string>;
    /**
     * 要删除的内容，用于存入操作日志
     * @type {string}
     * @memberof IdsDto
     */
    'param'?: string;
}

