/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// 789
// @ts-ignore
import type { CheckVo } from './check-vo';

/**
 * 122
 * 
 * @export
 * @interface IPageCheckVo
 */
export interface IPageCheckVo {
    /**
     * 
     * @type {number}
     * @memberof IPageCheckVo
     */
    'current'?: number;
    /**
     * 
     * @type {number}
     * @memberof IPageCheckVo
     */
    'pages'?: number;
    /**
     * 
     * @type {Array<CheckVo>}
     * @memberof IPageCheckVo
     */
    'records'?: Array<CheckVo>;
    /**
     * 
     * @type {boolean}
     * @memberof IPageCheckVo
     */
    'searchCount'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof IPageCheckVo
     */
    'size'?: number;
    /**
     * 
     * @type {number}
     * @memberof IPageCheckVo
     */
    'total'?: number;
}

