/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 122
 * 
 * @export
 * @interface LabelValueVo
 */
export interface LabelValueVo {
    /**
     * 显示
     * @type {string}
     * @memberof LabelValueVo
     */
    'label'?: string;
    /**
     * 值
     * @type {string}
     * @memberof LabelValueVo
     */
    'value'?: string;
}

