/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 122
 * 
 * @export
 * @interface PermissionDto
 */
export interface PermissionDto {
    /**
     * 
     * @type {string}
     * @memberof PermissionDto
     */
    'addTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof PermissionDto
     */
    'editTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof PermissionDto
     */
    'id'?: string;
    /**
     * 权限
     * @type {string}
     * @memberof PermissionDto
     */
    'permission'?: string;
    /**
     * 权限类型
     * @type {number}
     * @memberof PermissionDto
     */
    'permissionType'?: number;
    /**
     * 角色id
     * @type {string}
     * @memberof PermissionDto
     */
    'roleId'?: string;
    /**
     * 
     * @type {number}
     * @memberof PermissionDto
     */
    'version'?: number;
}

