/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 122
 * 
 * @export
 * @interface ResponseData
 */
export interface ResponseData {
    /**
     * 是否成功
     * @type {number}
     * @memberof ResponseData
     */
    'code'?: number;
    /**
     * 返回对象
     * @type {object}
     * @memberof ResponseData
     */
    'data'?: object;
    /**
     * 提示信息
     * @type {string}
     * @memberof ResponseData
     */
    'message'?: string;
}

