/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 122
 * 
 * @export
 * @interface RoleDto
 */
export interface RoleDto {
    /**
     * 
     * @type {string}
     * @memberof RoleDto
     */
    'addTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleDto
     */
    'editTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleDto
     */
    'id'?: string;
    /**
     * 备注
     * @type {string}
     * @memberof RoleDto
     */
    'remark'?: string;
    /**
     * 角色编码
     * @type {string}
     * @memberof RoleDto
     */
    'roleCode'?: string;
    /**
     * 角色名
     * @type {string}
     * @memberof RoleDto
     */
    'roleName'?: string;
    /**
     * 
     * @type {number}
     * @memberof RoleDto
     */
    'version'?: number;
}

