/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 122
 * 
 * @export
 * @interface UserDto
 */
export interface UserDto {
    /**
     * 账号
     * @type {string}
     * @memberof UserDto
     */
    'account'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'addTime'?: string;
    /**
     * 用户所有app权限值，用于shiro做资源权限的判断
     * @type {Set<string>}
     * @memberof UserDto
     */
    'appPerms'?: Set<string>;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'editTime'?: string;
    /**
     * 用户id
     * @type {string}
     * @memberof UserDto
     */
    'id'?: string;
    /**
     * 密码
     * @type {string}
     * @memberof UserDto
     */
    'password'?: string;
    /**
     * 用户所有pc权限值，用于shiro做资源权限的判断
     * @type {Set<string>}
     * @memberof UserDto
     */
    'pcPerms'?: Set<string>;
    /**
     * 用户所有权限值，用于shiro做资源权限的判断
     * @type {Set<string>}
     * @memberof UserDto
     */
    'perms'?: Set<string>;
    /**
     * 备注
     * @type {string}
     * @memberof UserDto
     */
    'remark'?: string;
    /**
     * 角色id(字符串_逗号分隔)
     * @type {string}
     * @memberof UserDto
     */
    'roleId'?: string;
    /**
     * 角色id(数组)
     * @type {Array<string>}
     * @memberof UserDto
     */
    'roleIds'?: Array<string>;
    /**
     * 角色名(字符串_逗号分隔)
     * @type {string}
     * @memberof UserDto
     */
    'roleName'?: string;
    /**
     * 用户所有角色值，用于shiro做角色权限的判断
     * @type {Set<string>}
     * @memberof UserDto
     */
    'roles'?: Set<string>;
    /**
     * 盐
     * @type {string}
     * @memberof UserDto
     */
    'salt'?: string;
    /**
     * 用户名
     * @type {string}
     * @memberof UserDto
     */
    'userName'?: string;
    /**
     * 
     * @type {number}
     * @memberof UserDto
     */
    'version'?: number;
}

