/* tslint:disable */
/* eslint-disable */
/**
 * V-PLUS
 * <div_style=\'font-size:14px;color:red;\'>RESTFUL_APIS</div>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: xxx@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 122
 * 
 * @export
 * @interface UserVo
 */
export interface UserVo {
    /**
     * 账号
     * @type {string}
     * @memberof UserVo
     */
    'account': string;
    /**
     * 主键id,编辑必传
     * @type {string}
     * @memberof UserVo
     */
    'id'?: string;
    /**
     * 用于记录操作日志的字段,删除则传被删除对象的名称,新增则传新增的名称,编辑则传原字段值+新字段值_编辑删除是必传
     * @type {string}
     * @memberof UserVo
     */
    'param'?: string;
    /**
     * 密码
     * @type {string}
     * @memberof UserVo
     */
    'password'?: string;
    /**
     * 备注
     * @type {string}
     * @memberof UserVo
     */
    'remark'?: string;
    /**
     * 角色id(数组)
     * @type {Array<string>}
     * @memberof UserVo
     */
    'roleIds'?: Array<string>;
    /**
     * 盐
     * @type {string}
     * @memberof UserVo
     */
    'salt'?: string;
    /**
     * 用户名
     * @type {string}
     * @memberof UserVo
     */
    'userName': string;
    /**
     * 乐观锁,编辑必传
     * @type {number}
     * @memberof UserVo
     */
    'version'?: number;
}

